# Generated by Django 4.2.7 on 2023-12-20 20:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0003_gallerypage_standardindexpage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Write some text to describe this page. This page is meant to host Gallery Page type subpages",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="gallerypage",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload a good quality image to Represent this gallery",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
