# Generated by Django 4.2.7 on 2023-12-24 08:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0004_galleryindexpage_gallerypage_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="goal_image",
            field=models.ForeignKey(
                blank=True,
                help_text="an Image to represent your vision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="mission_image",
            field=models.ForeignKey(
                blank=True,
                help_text="an Image to represent your vision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="partners",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Partner_infor",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "partner_logo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("partner_URL", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Patners",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="vision_image",
            field=models.ForeignKey(
                blank=True,
                help_text="an Image to represent your vision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
